version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password12345
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=jmeter_results
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token-123

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      # Map the provider config
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # Map the actual JSON dashboard files
      - ./dashboards:/var/lib/grafana/dashboards
  jmeter:
    image: justb4/jmeter:latest
    container_name: jmeter
    volumes:
      - ./scripts:/scripts        # Where your .jmx files live
      - ./results:/results        # Where local CSV/Log reports will go
    entrypoint: ["tail", "-f", "/dev/null"] # Keeps the container alive so we can run commands
  
volumes:
  influxdb-data:
  grafana-data: